# The filename must be .travis.yml, with "." !
sudo: required # Superdo/user level permissions
services:
  - docker # Installs the Docker CLI

before_install:
  # Build the Docker image. 
  # On build, the container ID is generated. Because Travis CI is automated and the ID is not known, the image needs to be tagged to be referenced later
  # Convention to have tag as: <you docker username>/<your docker repo name>
  - docker build -t abbeblubb/docker-react -f Dockerfile.dev .

script:
  - docker run abbeblubb/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-west-2-306476627547"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"

