# Only for dev/locally - therefore the .dev file ending, and the specific CMD step!
# Instead of "docker build .", use "docker build -f Dockerfile.dev .";
# the -f indicates you want to specify the file to be used to build out the image, and where the file is.

# Specify a base image
FROM node:alpine

# Container relative path
WORKDIR '/app'

# Install some depenendencies
# The only thing that the container needs to run properly, is the package.json, not the index.js
# package.json needs to be available *before* npm install
# Instead of first copying everything, copy just package.json
# Then second copy after RUN, with aim to reuse images (only second COPY will vary when update the files locally)
COPY package.json .
RUN npm install

# After npm install, copy over everything else
# Changes to index.js will thus not invalidate the steps above! (The cashed versions of the images will be reused - in a production project a rebuuild of one step can take minutes)
# . is relative to WORKDIR
# COPY is not really needed here, as this project requires volumes (se the docker-compose.yml), but COPY is still here if this Dockerfile.dev is used as base template for other images
COPY . .

# Default command to run on docker build . / docker build -f Dockerfile.dev .
CMD ["npm", "run", "start"]