version: "3.8"
services:
  client:
    build:
      context: .
      dockerfile: Dockerfile.dev
      # > Successfully tagged compose-volumes_client:latest
    restart: on-failure
    ports:
      - "3001:3000"
    volumes: 
      - .:/app
      - /app/node_modules
